export const mockFoodPosts = [
  {
    id: "1",
    donorId: "d1",
    donorName: "Raj Kumar",
    donorRating: 4.8,
    title: "Fresh Tomatoes",
    description: "Freshly harvested organic tomatoes from our farm. Great quality, perfect for cooking.",
    type: "vegetables",
    quantity: "10",
    unit: "kg",
    expiryDate: "2024-12-13",
    location: {
      district: "Kathmandu",
      city: "Kathmandu",
      address: "Thamel, Kathmandu",
      latitude: 27.7172,
      longitude: 85.3240,
    },
    pickupInstructions: "Call me before coming. Available from 10 AM to 6 PM.",
    imageUrl: "https://images.unsplash.com/photo-1592924357615-5042d17241a1?w=400&h=300&fit=crop",
    status: "Posted",
    createdAt: "2024-12-12T10:00:00Z",
    requests: [
      {
        id: "r1",
        recipientId: "rec1",
        recipientName: "Anita Sharma",
        postId: "1",
        status: "Pending",
        requestedAt: "2024-12-12T15:00:00Z",
      },
    ],
  },
  {
    id: "2",
    donorId: "d2",
    donorName: "Priya Patel",
    donorRating: 4.9,
    title: "Bakery Items - Bread & Pastries",
    description: "Unsold bakery items from today. Fresh bread, croissants, and pastries. Best before tomorrow.",
    type: "baked",
    quantity: "15",
    unit: "items",
    expiryDate: "2024-12-13",
    location: {
      district: "Lalitpur",
      city: "Lalitpur",
      address: "Kupondole, Lalitpur",
      latitude: 27.6923,
      longitude: 85.2916,
    },
    pickupInstructions: "Shop is open until 8 PM. Free delivery available within Lalitpur.",
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop",
    status: "Posted",
    createdAt: "2024-12-12T14:00:00Z",
    requests: [],
  },
  {
    id: "3",
    donorId: "d3",
    donorName: "Amit Singh",
    donorRating: 4.7,
    title: "Cooked Rice & Curry",
    description: "Home-cooked vegetable curry and rice. Made fresh today, packed in containers.",
    type: "cooked",
    quantity: "5",
    unit: "portions",
    expiryDate: "2024-12-13",
    location: {
      district: "Bhaktapur",
      city: "Bhaktapur",
      address: "Durbar Square, Bhaktapur",
      latitude: 27.6394,
      longitude: 85.4289,
    },
    pickupInstructions: "Please come within 2 hours. Food is warm and fresh.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    status: "Requested",
    createdAt: "2024-12-12T12:00:00Z",
    requests: [
      {
        id: "r2",
        recipientId: "rec2",
        recipientName: "Ramesh Thapa",
        postId: "3",
        status: "Accepted",
        requestedAt: "2024-12-12T13:00:00Z",
        acceptedAt: "2024-12-12T13:30:00Z",
      },
    ],
  },
  {
    id: "4",
    donorId: "d4",
    donorName: "Maya Gurung",
    donorRating: 4.6,
    title: "Organic Apples & Oranges",
    description: "Seasonal fruits - organic apples and oranges. Very fresh and sweet.",
    type: "fruits",
    quantity: "8",
    unit: "kg",
    expiryDate: "2024-12-15",
    location: {
      district: "Kathmandu",
      city: "Panauti",
      address: "Panauti Market",
      latitude: 27.6541,
      longitude: 85.4627,
    },
    pickupInstructions: "Available daily. Best to call ahead.",
    imageUrl: "https://images.unsplash.com/photo-1560807707-614bc9469f91?w=400&h=300&fit=crop",
    status: "Posted",
    createdAt: "2024-12-12T09:00:00Z",
    requests: [],
  },
  {
    id: "5",
    donorId: "d5",
    donorName: "Suresh Nair",
    donorRating: 4.5,
    title: "Milk & Dairy Products",
    description: "Fresh milk and paneer from today's production. High quality dairy.",
    type: "dairy",
    quantity: "5",
    unit: "lbs",
    expiryDate: "2024-12-14",
    location: {
      district: "Lalitpur",
      city: "Imadol",
      address: "Imadol Dairy Farm",
      latitude: 27.6580,
      longitude: 85.3289,
    },
    pickupInstructions: "Open from 6 AM to 8 PM. Cold storage available.",
    imageUrl: "https://images.unsplash.com/photo-1563636619-d0bb3b10af3f?w=400&h=300&fit=crop",
    status: "Accepted",
    createdAt: "2024-12-11T08:00:00Z",
    requests: [
      {
        id: "r3",
        recipientId: "rec3",
        recipientName: "Neha Verma",
        postId: "5",
        status: "Accepted",
        requestedAt: "2024-12-11T10:00:00Z",
        acceptedAt: "2024-12-11T11:00:00Z",
      },
    ],
  },
];

export const mockUsers = [
  {
    id: "d1",
    name: "Raj Kumar",
    email: "raj@example.com",
    phone: "9841000001",
    role: "donor",
    rating: 4.8,
    totalDonations: 12,
    totalRequests: 0,
    location: { district: "Kathmandu", city: "Kathmandu" },
    createdAt: "2024-01-15T00:00:00Z",
    isSuspended: false,
  },
  {
    id: "rec1",
    name: "Anita Sharma",
    email: "anita@example.com",
    phone: "9841000002",
    role: "recipient",
    rating: 4.5,
    totalDonations: 0,
    totalRequests: 5,
    location: { district: "Kathmandu", city: "Kathmandu" },
    createdAt: "2024-02-20T00:00:00Z",
    isSuspended: false,
  },
  {
    id: "admin1",
    name: "Admin User",
    email: "admin@foodshare.com",
    phone: "9841999999",
    role: "admin",
    rating: 5.0,
    totalDonations: 0,
    totalRequests: 0,
    location: { district: "Kathmandu", city: "Kathmandu" },
    createdAt: "2024-01-01T00:00:00Z",
    isSuspended: false,
  },
];

export const mockRequestHistory = [
  {
    id: "req1",
    recipientId: "rec1",
    postId: "1",
    donorId: "d1",
    status: "Completed",
    requestedAt: "2024-12-10T10:00:00Z",
    acceptedAt: "2024-12-10T11:00:00Z",
    pickedUpAt: "2024-12-10T15:00:00Z",
    completedAt: "2024-12-10T16:00:00Z",
  },
];
